apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-example
  labels:
    app: argocd-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-example
  template:
    metadata:
      labels:
        app: argocd-example
    spec:
      containers:
        - name: argocd-example
          image: ssuareza/argocd-example:latest
