apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-example-main
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ssuareza/argocd-example.git"
    targetRevision: main
    path: deploy/overlays/main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
