name: Docker Build & Push

on:
  push:
    branches:
      - main
      - dev
  workflow_run:
    workflows: ["CI - Lint & Test"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME//\//-}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/argocd-example:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/argocd-example:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/argocd-example:${{ env.BRANCH_NAME }}

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update Kustomize image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          kustomize edit set image $IMAGE_NAME=$IMAGE_NAME:$COMMIT_SHA

      - name: Commit and push updated kustomization.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add kustomization.yaml
          git commit -m "Update image tag to $COMMIT_SHA [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
